# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_output.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.backButton = QtWidgets.QPushButton(Form)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout.addWidget(self.backButton)

        self.forwardButton = QtWidgets.QPushButton(Form)
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout.addWidget(self.forwardButton)

        self.refreshButton = QtWidgets.QPushButton(Form)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout.addWidget(self.refreshButton)

        self.addressBar = QtWidgets.QLineEdit(Form)
        self.addressBar.setObjectName("addressBar")
        self.horizontalLayout.addWidget(self.addressBar)

        self.webView = QtWebEngineWidgets.QWebEngineView(Form)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")

        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.webView)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PyQtWebBrowser"))
        self.backButton.setText(_translate("Form", "Back"))
        self.forwardButton.setText(_translate("Form", "Forward"))
        self.refreshButton.setText(_translate("Form", "Refresh"))

from PyQt6 import QtWebEngineWidgets
